// <auto-generated />
using System;
using ExamSchedule.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSchedule.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ExamSchedule.Api.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("nguoi_dung", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext")
                        .HasColumnName("old_value");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId");

                    b.ToTable("nhat_ky", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.CaThi", b =>
                {
                    b.Property<int>("CaThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ca_thi_id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("HinhThucThi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("TrenMay")
                        .HasColumnName("hinh_thuc_thi");

                    b.Property<int>("KyThiId")
                        .HasColumnType("int")
                        .HasColumnName("ky_thi_id");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("PhongThiId")
                        .HasColumnType("int")
                        .HasColumnName("phong_thi_id");

                    b.Property<int>("RequiredProctorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("required_proctor_count");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("CaThiId");

                    b.HasIndex("KyThiId");

                    b.HasIndex("PhongThiId");

                    b.ToTable("ca_thi", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.DangKyThi", b =>
                {
                    b.Property<int>("DangKyThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dangkythi_id");

                    b.Property<int?>("CaThiId")
                        .HasColumnType("int")
                        .HasColumnName("ca_thi_id");

                    b.Property<int>("KyThiId")
                        .HasColumnType("int")
                        .HasColumnName("ky_thi_id");

                    b.Property<string>("LyDoChuaXep")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ly_do_chua_xep");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang_ky");

                    b.Property<int>("ThiSinhId")
                        .HasColumnType("int")
                        .HasColumnName("thisinh_id");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("trang_thai");

                    b.HasKey("DangKyThiId");

                    b.HasIndex("CaThiId");

                    b.HasIndex("KyThiId");

                    b.HasIndex("ThiSinhId", "KyThiId")
                        .IsUnique();

                    b.ToTable("dangkythi", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.KyThi", b =>
                {
                    b.Property<int>("KyThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ky_thi_id");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("LoaiChungChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("loai_chung_chi");

                    b.Property<string>("MaKyThi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_ky_thi");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_cap_nhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ten_ky_thi");

                    b.Property<DateTime>("ThoiGianBatDauDk")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian_bat_dau_dk");

                    b.Property<DateTime>("ThoiGianKetThucDk")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian_ket_thuc_dk");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("KyThiId");

                    b.HasIndex("MaKyThi")
                        .IsUnique();

                    b.ToTable("ky_thi", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.PhongThi", b =>
                {
                    b.Property<int>("PhongThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phong_thi_id");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ma_phong");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_phong");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vi_tri");

                    b.HasKey("PhongThiId");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("phong_thi", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ProctorAssignment", b =>
                {
                    b.Property<int>("ProctorAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phan_cong_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_phan_cong");

                    b.Property<int>("CaThiId")
                        .HasColumnType("int")
                        .HasColumnName("ca_thi_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_huy");

                    b.Property<int>("ProctorProfileId")
                        .HasColumnType("int")
                        .HasColumnName("giam_thi_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("vai_tro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.HasKey("ProctorAssignmentId");

                    b.HasIndex("ProctorProfileId");

                    b.HasIndex("CaThiId", "ProctorProfileId")
                        .IsUnique();

                    b.HasIndex("CaThiId", "Role")
                        .IsUnique();

                    b.ToTable("giam_thi_phan_cong", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ProctorProfile", b =>
                {
                    b.Property<int>("ProctorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("giam_thi_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("don_vi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_giam_thi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ProctorProfileId");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.ToTable("giam_thi", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("vai_tro", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ThiSinh", b =>
                {
                    b.Property<int>("ThiSinhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("thisinh_id");

                    b.Property<string>("DanToc")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dan_toc");

                    b.Property<string>("EmailCaNhan")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email_ca_nhan");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("Khoa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("khoa");

                    b.Property<string>("Lop")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lop");

                    b.Property<string>("MaThiSinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_thisinh");

                    b.Property<string>("NganhHoc")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nganh_hoc");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NoiSinh")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("noi_sinh");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("quoc_tich");

                    b.Property<string>("SoCccdHoChieu")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("so_cccd_ho_chieu");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<decimal?>("SoTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien");

                    b.HasKey("ThiSinhId");

                    b.HasIndex("MaThiSinh")
                        .IsUnique();

                    b.HasIndex("SoCccdHoChieu")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("thisinh", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("nguoi_dung_vai_tro", (string)null);
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.CaThi", b =>
                {
                    b.HasOne("ExamSchedule.Api.Entities.KyThi", "KyThi")
                        .WithMany("CaThis")
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSchedule.Api.Entities.PhongThi", "PhongThi")
                        .WithMany()
                        .HasForeignKey("PhongThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyThi");

                    b.Navigation("PhongThi");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.DangKyThi", b =>
                {
                    b.HasOne("ExamSchedule.Api.Entities.CaThi", "CaThi")
                        .WithMany("DangKyThis")
                        .HasForeignKey("CaThiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExamSchedule.Api.Entities.KyThi", "KyThi")
                        .WithMany()
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSchedule.Api.Entities.ThiSinh", "ThiSinh")
                        .WithMany("DangKyThis")
                        .HasForeignKey("ThiSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaThi");

                    b.Navigation("KyThi");

                    b.Navigation("ThiSinh");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ProctorAssignment", b =>
                {
                    b.HasOne("ExamSchedule.Api.Entities.CaThi", "CaThi")
                        .WithMany("ProctorAssignments")
                        .HasForeignKey("CaThiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamSchedule.Api.Entities.ProctorProfile", "ProctorProfile")
                        .WithMany("Assignments")
                        .HasForeignKey("ProctorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaThi");

                    b.Navigation("ProctorProfile");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.UserRole", b =>
                {
                    b.HasOne("ExamSchedule.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamSchedule.Api.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.CaThi", b =>
                {
                    b.Navigation("DangKyThis");

                    b.Navigation("ProctorAssignments");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.KyThi", b =>
                {
                    b.Navigation("CaThis");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ProctorProfile", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ExamSchedule.Api.Entities.ThiSinh", b =>
                {
                    b.Navigation("DangKyThis");
                });
#pragma warning restore 612, 618
        }
    }
}
